version: "3.9"

services:
  postgres:
    image: postgres:14     
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./tmp/pg-data:/var/lib/postgresql/data
    networks:
      - tuna-net
  server:
    container_name: practicum-game
    image: practicum-game
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
        SERVER_API: ${SERVER_API}
    env_file:
      - .env
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - postgres
    volumes:
      - ./packages/server:/app/packages/server
    networks:
      - tuna-net
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - server
    networks:
      - tuna-net

networks:
  tuna-net:
    driver: bridge

volumes:
  pg-data:
