version: "3.9"

services:
  postgres:
    image: postgres:14     
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./tmp/pg-data:/var/lib/postgresql/data
    networks:
      - tuna-net
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.6
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
    ports:
      - "8080:${PGADMIN_PORT}"
    volumes:
      - ./tmp/pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - tuna-net

networks:
  tuna-net:
    driver: bridge

volumes:
  pg-data:
  pgadmin-data:
